### Appendix 2:  Tag Deployment fields

The fields required for a motus tag deployment record are:

tagID
: Unique numeric ID assigned to the tag, provided at the
time of tag registration.

status
: Status from one of the possible following values:
pending, deploy, terminate. "pending” indicates that the
deployment record isn’t ready to be finalized for deployment
yet. "deploy” indicates that the deployment can be
activated. "terminate” will attempt to finalize a deployment by
providing an end date. Note that deployments can only be
activated or terminated if all required information has been
provided. Attempts to deploy or terminate an incomplete
deployment will return an error. At the moment, several of the
parameters can no longer be modified once a deployment is
activated, and the status cannot be changed back to an earlier
status (permitted sequence is pending -> deploy -> terminate,
but levels can be omitted).

tsStart
: Timestamp for start of deployment. If the tag has a
deferred time lag (deferTime), this is the time at which the
tag is activated, in such a way that the time when the tag is
expected to be active is given by tsStart + deferTime.

tsEnd
 : [optional] Timestamp for end of deployment. Required
for status=terminate.

deferTime
 : [optional] Defer time (in seconds from
tsStart). Some tags are capable of deferred activation - they
don't start transmitting until some (possibly large) number of
seconds after activation.

speciesID
 : [optional] Numeric ID (integer) of the species on
which the tag is being deployed. You can obtain this value by
using `motusListSpecies()` to search by name or code.

markerType
 : [optional] Type of marker
(e.g. "metal band”, "color band”)

markerNumber
 : [optional] Marker number or descriptor
(e.g. "1234-56789” or "L:Red/Blue,R:Metal 1234-56789”)

lat
 : [optional] Latitude (decimal degrees) of the deployment
site. E.g. 45.123.

lon
 : [optional] Longitude (decimal degrees) of the deployment
site. E.g. -60.325.

elev
 : [optional] Elevation above sea level (meters) of the
deployment site. E.g. 23.

comments
 : [optional] can be plain text, or a JSON-formatted string
giving additional parameters

ts
 : [optional] Time at which deployment information
was generated.  Defaults to time at which function is called.
