<?php
/***

   This script generates the status download page at https://sgdata.motus.org/status2
   It requires authentication via apache's mod_auth_tkt.  The authentication cookie
   is generated by the script login.php  This is the version using the API back-end,
   instead of the soon-to-be-deprecated original status server.  Replies from the
   back-end are bz2-compressed JSON objects.

   API documentation is here:

   https://github.com/jbrzusto/motusServer/blob/new_server/inst/doc/status_api.md

   GET parameters for this script.
   - n: maximum number of jobs to show (must be <= 500); default 20
   - k: max jobID to show (0 means unknown); if negative, - min jobID to show; default 0

 ***/

// back-end API server, and various entries
$STATUS_SERVER_URL = 'http://127.0.0.1:22439/status2/';

$API_STATUS_INFO     = $STATUS_SERVER_URL . '/status_api_info';
$API_LIST_JOBS       = $STATUS_SERVER_URL . '/list_jobs';
$API_SUBJOBS_FOR_JOB = $STATUS_SERVER_URL . '/subjobs_for_job';

// parameters
$n = isset($_GET['n']) ? $_GET['n'] : 20;
$k = isset($_GET['k']) ? $_GET['k'] : 0;

// the status API allows us to use the auth_tkt cookie for authentication.
$authToken = $_COOKIE['auth_tkt'];


// function to post to a uri and return the json-decoded bzuncompressed reply
// $url: URL of request
// $par: array of items to be included in 'json' request object
// $auth: authentication object, to be added as 'authToken' to request object

function post ($url, $par, $auth) {
    $ch = curl_init($url);
    $par['authToken'] = $auth;
    $json = 'json=' . urlencode(json_encode($par));
    curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
    curl_setopt($ch, CURLOPT_HEADER, true);
    curl_setopt($ch, CURLOPT_HTTPHEADER, array('Content-Type: application/x-www-form-urlencoded'));
    curl_setopt($ch, CURLOPT_POSTFIELDS,  $json);
    $res = curl_exec($ch);
    curl_close($ch);
    return(json_decode(bzdecompress($res), true));
}


?>
    <html>
    <head>
        <title>Status of Motus Processing Version 2 (using API back-end)</title>
        <script language="javascript" type="text/javascript"
                src="/javascript/jquery/jquery.min.js"></script>
    </head>
    <body>
        <h3> Status of your motus data-processing jobs </h3>
        <div id="job_status">
            <pre>
            <?php
            echo (post($API_LIST_JOBS, array(), $authToken));
            ?>
            </pre>
        </div>
    </body>
</html>
