<?php
/***

   This script generates the status download page at https://sgdata.motus.org/status
   It requires authentication via apache's mod_auth_tkt.  The authentication cookie
   is generated by the script login.php

   We show users the status of the server, and of any jobs they have submitted.

   This script wraps calls to the local motusStatusServer process.

   GET parameters:
   - n: maximum number of jobs to show (must be <= 500); default 20
   - k: max jobID to show (0 means unknown); if negative, - min jobID to show; default 0

 ***/

// database with project info
$STATUS_SERVER_URL = 'http://127.0.0.1:59059/custom/';

// parameters
$n = isset($_GET['n']) ? $_GET['n'] : 20;
$k = isset($_GET['k']) ? $_GET['k'] : 0;

// extract userid from already-validated ticket
$parts = explode("!", $_COOKIE['auth_tkt']);
$user = substr($parts[0], 40);
if ($parts[2] == "administrator") {
    $user = "john";
}
// URL for internal server to fetch current page of jobs
$current_job_page = $STATUS_SERVER_URL . 'latestJobsApp?user=' . $user . '&n=' . $n . '&k=' . $k;

?>
<html>
    <head>
        <title>Status of Motus Processing</title>
        <script language="javascript" type="text/javascript"
                src="/javascript/jquery/jquery.min.js"></script>
    </head>
    <body>
        <h3> Status of your motus data-processing jobs </h3>
        <div id="job_status">
            <?php
            $table = file_get_contents($current_job_page);
            // make normal links clickable; not every embedded URL is handled,
            // as some are not already URL-encoded
            echo eregi_replace(' (https?://[^ ]+)', ' <a href="\\1">\\1</a>', $table);
            ?>
        </div>
    </body>
</html>
