<?php
/***

   This script generates the status download page at https://sgdata.motus.org/status2
   It requires authentication via apache's mod_auth_tkt.  The authentication cookie
   is generated by the script login.php  This is the version using the API back-end,
   instead of the soon-to-be-deprecated original status server.  Replies from the
   back-end are bz2-compressed JSON objects.

   API documentation is here:

   https://github.com/jbrzusto/motusServer/blob/new_server/inst/doc/status_api.md

   GET parameters for this script.
   - n: maximum number of jobs to show (must be <= 500); default 20
   - k: max jobID to show (0 means unknown); if negative, - min jobID to show; default 0

 ***/

// back-end API server, and various entries
$STATUS_SERVER_URL = 'https://sgdata.motus.org/status2';
// if we know this script will run from the same server, we can use this
// direct URL to save one layer of forwarding with encryption overhead.
// $STATUS_SERVER_URL = 'http://localhost:22439/custom';

$API_STATUS_INFO     = $STATUS_SERVER_URL . '/status_api_info';
$API_LIST_JOBS       = $STATUS_SERVER_URL . '/list_jobs';
$API_SUBJOBS_FOR_JOB = $STATUS_SERVER_URL . '/subjobs_for_job';

// parameters
$n = isset($_GET['n']) ? $_GET['n'] : 20;
$k = isset($_GET['k']) ? $_GET['k'] : 0;

// the status API allows us to use the auth_tkt cookie for authentication.
$authToken = $_COOKIE['auth_tkt'];


// function to post to a uri and return the json-decoded bzuncompressed reply
// $url: URL of request
// $par: array of items to be included in 'json' request object
// $auth: authentication object, to be added as 'authToken' to request object
//
// Note that this function runs on the server side, so the API call happens
// from there and requires use of the X-Forwarded-For header to pass the
// client's IP address.

function post ($url, $par) {
    global $authToken;
    $ch = curl_init($url);
    $par['authToken'] = $authToken;
    $json = 'json=' . urlencode(json_encode($par));
    curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
    curl_setopt($ch, CURLOPT_HEADER, false);
    curl_setopt($ch, CURLOPT_HTTPHEADER, array('Content-Type: application/x-www-form-urlencoded', 'X-Forwarded-For: ' . $_SERVER['REMOTE_ADDR']));
    curl_setopt($ch, CURLOPT_POSTFIELDS,  $json);
    $res = curl_exec($ch);
    curl_close($ch);
    return(json_decode(bzdecompress($res), true));
}


?>
<html>
    <head>
        <title>Status of Motus Processing Version 2 (using API back-end)</title>
    </head>
    <body>
        <h3> Status of your motus data-processing jobs </h3>
        <div id="job_status">
            <pre>
                <?php
                $tbl = post($API_LIST_JOBS,
                            array(
                                'options' => array(
                                    'includeUnknownProjects' => true,
                                ),
                                'order' => array(
                                    'sortBy' => 'mtime desc'
                                )
                            )
                );
                ?>
                <table id="jobs">
                    <tr>
                        <th>ID</th><th>MotusUserID</th><th>Type</th><th>Created</th><th>Last Activity</th><th>Status</th>
                    </tr>
                    <?php
                    $n = count($tbl['id']);
                    for ($i=0; $i < $n; $i++) {
                        $cdate = strftime("%Y %m %d %H:%M:%S", $tbl['ctime'][$i]);
                        echo ("<tr class=\"jobSummary\" id=\"job{$tbl['id'][$i]}\"><td>{$tbl['id'][$i]}</td><td>{$tbl['motusUserID'][$i]}</td><td>{$tbl['type'][$i]}</td><td>$cdate</td><td>{$tbl['mtime'][$i]}</td><td>{$tbl['done'][$i]}</td></tr>");
                    }
                    ?>
                </table>
            </pre>
        </div>
    </body>
</html>
