#' run the tag finder on one sensorgnome boot session, in the new style.
#'
#' Called by \code{\link{server}}.
#'
#' Runs the new tag finder for one boot session of a single SG.
#' The files for that boot session have already been merged into
#' the DB for that receiver.
#'
#' @param j the job, with these properties:
#' \itemize{
#' \item serno serial number of receiver (including leading 'SG-')
#' \item monoBN monotonic boot session number
#' \item boolean TRUE or FALSE; can the tag finder be run with \code{--resume}?
#' }
#'
#' @return TRUE on success, or FALSE if the tag finder has an error.
#'
#' @note if topJob(j) contains fields motusUserID and motusProjectID, these are
#' recorded in the receiver database for the batch generated by this call.
#'
#' @seealso \code{\link{server}}
#'
#' @export
#'
#' @author John Brzustowski \email{jbrzusto@@REMOVE_THIS_PART_fastmail.fm}

handleSGfindtags = function(j) {

    serno = j$serno

    jobLog(j, paste0("Running tag finder on receiver ", serno, " boot session ", j$monoBN, if (j$canResume) " (resumed)"))

    ## lock this receiver's DB

    lockSymbol(serno)

    ## make sure we unlock the receiver DB when this function exits, even on error
    ## NB: the runMotusProcessServer script also drops any locks held by a given
    ## processServer after the latter exits.

    on.exit(lockSymbol(serno, lock=FALSE))

    src = getRecvSrc(serno)

    ## get parameter overrides
    por = getParamOverrides(serno, monoBN = j$monoBN)
    if (por != "")
        jobLog(j, paste0("Got parameter overrides: ", por))

    rv = NULL
    ## run the tag finder
    tryCatch({
        rv = sgFindTags(src, getMotusMetaDB(), resume=j$canResume, par = paste(sgDefaultFindTagsParams, por), mbn=j$monoBN)
    }, error = function(e) {
        jobLog(j, paste(as.character(e), collapse="   \n"))
    })

    if (! is.null(rv)) {
        ## record motus user and project IDs for this batch, which may
        ## be present in the top job (typically an "uploadFile" job)

        tj = topJob(j)
        muid = tj$motusUserID
        mpid = tj$motusProjectID
        if (! is.null(muid) && ! is.null(mpid))
            dbGetQuery(src$con, sprintf("update batches set motusUserID=%d, motusProjectID=%d where batchID=%d", muid, mpid, rv$batchID))
    }

    closeRecvSrc(src)

    if (is.null(rv))
        return(FALSE)

    jobLog(j, paste0("Got ", rv$numHits, " (unfiltered) detections."))
    return(TRUE)
}
