#' Constants for the motus package.
#'
#' API entry points:
#'

MOTUS_API_ENTRY_POINTS          = 'http://motus.org/data/api/entrypoints.jsp'
MOTUS_API_REGISTER_TAG          = 'http://motus.org/data/api/v1.0/registertag.jsp'
MOTUS_API_DEPLOY_TAG            = 'http://motus.org/data/api/v1.0/deploytag.jsp'
MOTUS_API_REGISTER_PROJECT      = 'http://motus.org/data/api/v1.0/registerproject.jsp'
MOTUS_API_REGISTER_RECEIVER     = 'http://motus.org/data/api/v1.0/registersensor.jsp'
MOTUS_API_LIST_PROJECTS         = 'http://motus.org/data/api/v1.0/listprojects.jsp'
MOTUS_API_RECEIVER_STATUS       = 'http://motus.org/data/api/v1.0/listreceiverstatus.jsp'
MOTUS_API_LIST_TAGS             = 'http://motus.org/data/api/v1.0/listtags.jsp'
MOTUS_API_LIST_SENSORS          = 'http://motus.org/data/api/v1.0/listsensors.jsp'
MOTUS_API_LIST_SENSOR_DEPS      = 'http://motus.org/data/api/v1.0/listsensordeployments.jsp'
MOTUS_API_LIST_SPECIES          = 'http://motus.org/data/api/v1.0/listspecies.jsp'
MOTUS_API_SEARCH_TAGS           = 'http://motus.org/data/api/v1.0/searchtags.jsp'
MOTUS_API_DEBUG                 = 'http://motus.org/data/api/v1.0/debug.jsp'
MOTUS_API_DELETE_TAG_DEPLOYMENT = 'http://motus.org/data/api/v1.0/deletetagdeployment.jsp'

# a list of field names which must be formatted as floats so that
# the motus API recognizes them correctly.  This means that if they
# happen to have integer values, a ".0" must be appended to the JSON
# field value.  We do this before sending any query.  This is
# only required due to motus using a crappy JSON parser.

MOTUS_FLOAT_FIELDS = c("tsStart", "tsEnd", "regStart", "regEnd",
"offsetFreq", "period", "periodSD", "pulseLen", "param1", "param2",
"param3", "param4", "param5", "param6", "ts", "nomFreq", "deferTime", "lat", "lon", "elev")

## a regular expression for replacing values that need to be floats
## Note: only works for named scalar parameters; i.e. "XXXXX":00000

MOTUS_FLOAT_REGEX = sprintf("((%s):-?[0-9]+)([,}])",
                             paste(sprintf("\"%s\"", MOTUS_FLOAT_FIELDS), collapse="|"))

## a pre-amble that gets pasted before upload tokens so they can easily be found in emails

MOTUS_UPLOAD_TOKEN_PREFIX = "3cQejZ7j"

## the regular expression for recognizing an authorization token in an email

MOTUS_UPLOAD_TOKEN_REGEX = paste0(MOTUS_UPLOAD_TOKEN_PREFIX, "(?<token>[A-Za-z0-9]{10,100})")

## format of date/time in logfiles

MOTUS_LOG_TIME_FORMAT = "%Y-%m-%dT%H-%M-%OS6"

## format of date/time in queue entries (file or folder names)

MOTUS_TIMESTAMP_FORMAT = "%Y-%m-%dT%H-%M-%OS6"

## format of date/time in SG filenames
MOTUS_SG_TIMESTAMP_FORMAT = "%Y-%m-%dT%H-%M-%OS4"

## regex to match a leading timestamp
MOTUS_LEADING_TIMESTAMP_REGEX = "^(?<timestamp>[0-9]{4}-[0-9]{2}-[0-9]{2}T[0-9]{2}-[0-9]{2}-[0-9]{2}\\.[0-9]{1,9})"

## regex to match a full filename for a compressed message
MOTUS_COMPRESSED_EMAIL_REGEX = paste0(MOTUS_LEADING_TIMESTAMP_REGEX, "\\.bz2$")

## separator used in queue filenames
MOTUS_QUEUE_SEP = ","

## regex to match queue items generated by motus package
MOTUS_QUEUEFILE_REGEX = paste0(MOTUS_LEADING_TIMESTAMP_REGEX, MOTUS_QUEUE_SEP, "(?<params>.*)$")

## "From" address for outgoing emails

MOTUS_OUTGOING_EMAIL_ADDRESS = "no-reply@sensorgnome.org"

## name of archive to hold "bad" files; this archive is stored in the folder
## for each top-level job; we append "NOAUTO" to the name to prevent it
## being treated as a downloaded file.

MOTUS_BADFILE_ARCHIVE = "bad_files.zip.NOAUTO"

## filesystem layout; dirs end in "/"

#'@export

MOTUS_PATH = list(
    ROOT             = "/sgm",
    BIN              = "/sgm/bin",             ## executable scripts
    CACHE            = "/sgm/cache",           ## recent results of large queries from motus.org
    CRYPTO           = "/sgm/crypto",          ## public/private keypairs for ssh etc. by receivers
    DONE             = "/sgm/done",            ## folders for completed jobs
    DOWNLOADS        = "/sgm/downloads",       ## manually-downloaded files; downloadXXX() checks here before (re) grabbing file
    ERRORS           = "/sgm/errors",          ## save dumped call stacks of server errors
    INBOX            = "/sgm/inbox",           ## emails go here, unless /sgm/EMBARGO exists
    INBOX_EMBARGOED  = "/sgm/inbox_embargoed", ## incoming emails under embargo (not processed)
    INCOMING         = "/sgm/incoming",        ## files / dirs moved here are processed by server(); this is the external / asynchronous
                                               ## access point to the processing queue
    LOCKS            = "/sgm/locks",           ## locks for process queues and receiver DBs
    LOGS             = "/sgm/logs",            ## processing logs
    MAIL_QUEUE       = "/sgm/email_queue",     ## queue for processing emails by emailServer()
    MANUAL           = "/sgm/manual",          ## folders needing manual attention
    MOTR             = "/sgm/motr",            ## links to receiver DBs by motus ID
    OLDROOT          = "/SG",                  ## root of old-style folder hierarchy
    OUTBOX           = "/sgm/outbox",          ## copies of all sent emails
    OUTBOX_EMBARGOED = "/sgm/outbox_embargoed",  ## unsent outgoing emails
    PLOTS            = "/sgm/plots",           ## generated plots
    PUB              = "/sgm/pub",             ## web-visible public content
    QUEUES           = "/sgm/queue",           ## queues for processing items
    QUEUE0           = "/sgm/queue/0",         ## queue 0 is watched for new entries by each of the processServers;
                                               ## at most one of them will claim the new job.
    QUEUE1           = "/sgm/queue/1",         ## queue 1..8 for processServers
    QUEUE2           = "/sgm/queue/2",
    QUEUE3           = "/sgm/queue/3",
    QUEUE4           = "/sgm/queue/4",
    QUEUE5           = "/sgm/queue/5",
    QUEUE6           = "/sgm/queue/6",
    QUEUE7           = "/sgm/queue/7",
    QUEUE8           = "/sgm/queue/8",
    RECV             = "/sgm/recv",            ## receiver databases
    RECVLOG          = "/sgm/recvlog",         ## logfiles from receivers
    REFS             = "/sgm/refs",            ## links to receiver DBs by year, projCode, siteCode
    SPAM             = "/sgm/spam",            ## saved invalid emails
    TAGS             = "/sgm/tags",            ## ??
    TAGREG_CLEANUP   = "/sgm/tagregCleanup.R", ## script to provided tag registration cleanups downstream from motus
    TMP              = "/sgm/tmp"              ## intermediate storage; persistent across reboots
)

## main logfile name
MOTUS_MAINLOG_NAME = "mainlog.txt"

## default file mode for new files, folders:
MOTUS_DEFAULT_FILEMODE = "0750"

## compressed archives we can handle
MOTUS_ARCHIVE_SUFFIXES = c(
    "zip",
    "7z",
    "rar"
)

MOTUS_ARCHIVE_REGEX = paste0("(?i)\\.(?<suffix>",
                             paste(MOTUS_ARCHIVE_SUFFIXES, collapse="|"),
                             ")$")

## allowed file suffixes for emailed data files:

MOTUS_FILE_ATTACHMENT_SUFFIXES = c(
    MOTUS_ARCHIVE_SUFFIXES,
    "txt",                 ## Some users directly attach raw sensorgome files
    "txt\\.gz",            ## to an email.
    "dta"                  ## File from lotek receiver
    )

## regex to match filenames against for checking suffix

MOTUS_FILE_ATTACHMENT_REGEX = paste0("(?i)\\.(?<suffix>",
                                     paste(MOTUS_FILE_ATTACHMENT_SUFFIXES, collapse="|"),
                                     ")$")


## regex to match receiver serial numbers (adapted from sgFilenameRegex, which differs
## in not using the 'SG-' prefix).

MOTUS_SG_SERNO_REGEX = "(?<serno>SG-[0-9A-Z]{4}(?:RPi2|BBBK|BB)[0-9A-Z]{4,6}(_[0-9])?)"

## deprecated: path to db for looking up proj, site by serial number
## and timestamp or bootnumber. This is for generating output in the
## old format.

MOTUS_RECV_MAP_DB = "/SG/receiver_map.sqlite"

## regex for matching DOS filenames (names of SG data files which have
## been shortened to 8.3 form)
## see https://en.wikipedia.org/wiki/8.3_filename#VFAT_and_Computer-generated_8.3_filenames

MOTUS_DOS_FILENAME_REGEX = "^[a-zA-Z0-9]+~[0-9].(GZ|TXT)"

## the unfortunate individual who receives emails when things need attention
#'@export

MOTUS_ADMIN_EMAIL = "jbrzusto@fastmail.fm"

## the sensorgnome.org username for the administrator

MOTUS_ADMIN_USERNAME = "john"

## the database used to record server activity
MOTUS_SERVER_DB = "/sgm/server.sqlite"

## the table used to record locks on receivers
MOTUS_RECEIVER_LOCK_TABLE = "recvLocks"

## regex for files we want to delete.
## Just about every OS these days writes indexing info to
## flash drives, and we often get these files in a transfer.

MOTUS_JUNKFILE_REGEX = "(__MACOSX/|System Volume Information/|._.DS_Store)"
