#' enqueue a job
#'
#' Add a job to the global MOTUS_QUEUE.
#'
#' @param j the job to add; e.g. as generated by \link{\code{newJob}}
#'
#' @return no return value
#'
#' @note If the job is already in the queue, this function does nothing.
#' If the job is marked "done", it is not added to the queue.
#'
#' @export
#'
#' @author John Brzustowski \email{jbrzusto@@REMOVE_THIS_PART_fastmail.fm}

queueJob = function(j) {
    if (j %in% QUEUE || isTRUE(j$done))
        return()

    QUEUE <<- c(QUEUE, j)
}
